name: plaid
description: Porting of Plaid Api (https://plaid.com/docs/) to Flutter.
version: 0.0.1
author: Brian Schardt<brian.ja.schardt@gmail.com>
homepage: https://github.com/prototype-two/flutter_plaid

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  webview_flutter: ^0.3.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
